var studentName = "Kubea";
var studentAge = 24;
var totalMarks = 450;
var averageScore = 75;
var courseId = 2001;
var departmentName = "ComputerScience";
var rollNumber = 21124016;
var subjectCount = 6;
var classTeacher = "Mr.X";
var schoolName = "ABC School";
var isPassed = true;
var totalStudents = 60;
var userEmail = "kubea2004@gmail.com";
var userPassword = "abc123";
var userPhone = 975174548;
var clientName = "Mr.Y";
var branchCode = "TN01";
var employeeSalary = 25000;
var employeeId = "EMP1024";
var joiningDate = "2025-10-21";
var projectTitle = "Fatigue Detection";
var companyName = "TechCare";
var locationName = "Tiruppur";
var productPrice = 999;

console.log(studentName);
console.log(studentAge);
console.log(totalMarks);
console.log(averageScore);
console.log(courseId);
console.log(departmentName);
console.log(rollNumber);
console.log(subjectCount);
console.log(classTeacher);
console.log(schoolName);
console.log(isPassed);
console.log(totalStudents);
console.log(userEmail);
console.log(userPassword);
console.log(userPhone);
console.log(clientName);
console.log(branchCode);
console.log(employeeSalary);
console.log(employeeId);
console.log(joiningDate);
console.log(projectTitle);
console.log(companyName);
console.log(locationName);
console.log(productPrice);


let student_name = "Arun";
let student_age = 22;
let total_marks = 480;
let average_score = 80;
let course_id = 3002;
let department_name = "InformationTechnology";
let roll_number = 21124018;
let subject_count = 5;
let class_teacher = "Ms.Priya";
let school_name = "XYZ College";
let is_passed = false;
let total_students = 55;
let user_email = "arun.it22@gmail.com";
let user_password = "pass@123";
let user_phone = 9876543210;
let client_name = "Mr.Z";
let branch_code = "TN02";
let employee_salary = 32000;
let employee_id = "EMP2048";
let joining_date = "2024-06-15";
let project_title = "AI Attendance System";
let company_name = "SmartTech";
let location_name = "Coimbatore";
let product_price = 1599;

console.log(student_name);
console.log(student_age);
console.log(total_marks);
console.log(average_score);
console.log(course_id);
console.log(department_name);
console.log(roll_number);
console.log(subject_count);
console.log(class_teacher);
console.log(school_name);
console.log(is_passed);
console.log(total_students);
console.log(user_email);
console.log(user_password);
console.log(user_phone);
console.log(client_name);
console.log(branch_code);
console.log(employee_salary);
console.log(employee_id);
console.log(joining_date);
console.log(project_title);
console.log(company_name);
console.log(location_name);
console.log(product_price);